function dy = calculate_cdmtheta_strong(u_m,theta,A_k,A_m,alpha_b,alpha_nu,...
    f1,kappa,kappa21)
%{
psi = [Theta1, Theta1', Delta_ph , g_ph,
    theta1, theta1',Delta_c,g_c, nu_turnon]
%}

F = (1+(kappa+(1-kappa)*kappa21/(1+kappa21))*sqrt(u_m/A_m)...
    +8/3*u_m^2*f1*(1-cos(theta(1))))...
    /(1-4/3*u_m^2*f1*theta(2)^2);
C = 1/F;

if theta(9) == 1
    Phi = (u_m*F*theta(2)*theta(6)+u_m*sin(theta(1))*theta(5)+1.5*F*theta(2)*theta(5)+...
        3/8/f1/u_m*(theta(3)*(1+3/4*kappa*sqrt(u_m/A_m))...
        +(1-kappa)*kappa21/(1+kappa21)*sqrt(u_m/A_m)*theta(7)))/...
        (u_m*F*theta(2)^2-A_k/f1);
    Phi_p_term = f1*theta(2)*theta(5)...
        -theta(4)*C/4/u_m*(1+3/4*kappa*sqrt(u_m/A_m))...
        -C/4/u_m*(1-kappa)*kappa21/(1+kappa21)*sqrt(u_m/A_m)*theta(8);
    %This is the term d(phi)/d(u_m)+phi/(2u_m)
else
    Phi = (u_m*F*theta(2)*theta(6)+u_m*sin(theta(1))*theta(5)+1.5*F*theta(2)*theta(5)+...
        3/8/f1/u_m*(theta(3)*(1/(1+alpha_nu)+3/4*kappa*sqrt(u_m/A_m))+...
        (1-kappa)*kappa21/(1+kappa21)*sqrt(u_m/A_m)*theta(7)))/...
        (u_m*F*theta(2)^2-A_k/f1);
    Phi_p_term = f1*theta(2)*theta(5)...
        -theta(4)*C/4/u_m*(1/(1+alpha_nu)+3/4*kappa*sqrt(u_m/A_m))...
        -C/4/u_m*(1-kappa)*kappa21/(1+kappa21)*sqrt(u_m/A_m)*theta(8);
end
const_Del = theta(3)/2/u_m/(1+3/4*alpha_b*sqrt(u_m/A_m));
const_g = 2*f1*u_m*theta(2)^2*theta(4)+...
    C/u_m*(1+3/4*(kappa+(1-kappa)*kappa21/(1+kappa21))*sqrt(u_m/A_m))*theta(4);
const_gc = 2*f1*u_m*theta(2)^2*theta(8)+...
    C/u_m*(1+3/4*(kappa+(1-kappa)*kappa21/(1+kappa21))*sqrt(u_m/A_m))*theta(8);

     dy = zeros(9,1); % a column vector
     dy(1) = theta(2);
     dy(2) = -theta(2)/u_m*(5/2-2*u_m^2*f1*theta(2)^2-...
         (1+3/4*(kappa+(1-kappa)*kappa21/(1+kappa21))*(u_m./A_m).^(1/2))*C)...
         -sin(theta(1))*C;
     dy(3) = 2*A_k*C/3*theta(4)+4*Phi_p_term+const_Del+const_g;
     dy(4) = -const_Del-const_g-2*Phi/u_m;
     dy(5) = theta(6);
     dy(6) = -theta(6)/u_m*(2.5-2*u_m^2*f1*theta(2)^2 ...
         -C*(1+3/4*(kappa+(1-kappa)*kappa21/(1+kappa21))*sqrt(u_m/A_m)))-...
         C*theta(5)*(A_k/u_m+cos(theta(1)))...
         +4*Phi_p_term*theta(2)-2*Phi*(theta(2)/u_m+C*sin(theta(1)));
     dy(7) = const_gc+2*A_k*C/3*theta(8)+3*Phi_p_term;
     dy(8) = -const_gc-3*Phi/2/u_m;
     if theta(9) == 1
         if theta(3)<=0
             dy(9) = 1000;
         else
             dy(9) = 0;
         end
     else
         dy(9) = 0;
     end