function dy = calculate_bytheta_weak_appox(u_m,theta,A_k,A_m,alpha0,beta0,...
    alpha_nu,epsilon01,epsilon02,f1,f2,mu,kappa)
%psi = [Delta_ph, Del_ph_p ,phic1 ,phis1, phic2 phis2,nu_turnon,Delta_b,Del_b_p]
F = 1 + kappa*sqrt(u_m/A_m)+8/3*f1*sqrt(u_m)*epsilon01+...
    8/3*f2*sqrt(u_m)*epsilon02;
C = 1/F;
delta1 = 1-epsilon01*u_m^(-1.5)/4;
delta2 = 1-epsilon02*u_m^(-1.5)/4/mu^2;
if theta(7) == 1
    Phi = -epsilon01*f1/A_k*u_m^(-1/2)*(2*theta(3)-3*sqrt(F)/2/u_m*theta(4))...
        -epsilon02*f2/A_k*u_m^(-1/2)*(2*theta(5)-3*sqrt(F)/2/u_m/mu*theta(6))...
        -3/8/A_k/u_m*(theta(1)+kappa*sqrt(u_m/A_m)*theta(8));
else
    Phi = -epsilon01*f1/A_k*u_m^(-1/2)*(2*theta(3)-3*sqrt(F)/2/u_m*theta(4))...
        -epsilon02*f2/A_k*u_m^(-1/2)*(2*theta(5)-3*sqrt(F)/2/u_m/mu*theta(6))...
        -3/8/A_k/u_m*(theta(1)/(1+alpha_nu)+kappa*sqrt(u_m/A_m)*theta(8));
end

     dy = zeros(9,1); % a column vector
     dy(1) = theta(2);
     dy(2) = -(alpha0/(alpha0+beta0/sqrt(u_m)))/2/u_m*(A_k/3/sqrt(F)*u_m^1.5/...
         (alpha0+beta0/sqrt(u_m))+1)*theta(2)-(3-C)/4/u_m*theta(2)...
         -A_k/3*beta0/(alpha0*sqrt(u_m)+beta0)/u_m/F*theta(1)...
         -4/3*Phi*A_k/u_m*C;
     dy(3) = A_k/2/u_m/delta1*sqrt(C)*theta(4)...
         +3/32/u_m^2/delta1/sqrt(F)*theta(4);
     dy(4) = -A_k/2/u_m/delta1*sqrt(C)*theta(3)...
         -Phi*sqrt(C)/delta1-3/32/u_m^2/delta1/sqrt(F)*theta(3)...
         +epsilon01/4/sqrt(F)/delta1/u_m^1.5*theta(3);
     dy(5) = A_k/2/u_m/mu/delta2*sqrt(C)*theta(6)...
         +3/32/u_m^2/mu/delta2/sqrt(F)*theta(6);
     dy(6) = -A_k/2/u_m/mu/delta2*sqrt(C)*theta(5)...
         -mu*Phi*sqrt(C)/delta2-3/32/u_m^2/mu/delta2/sqrt(F)*theta(5)...
         +epsilon02/4/sqrt(F)/mu/delta2/u_m^1.5*theta(5);
     if theta(7) == 1
         if theta(1)<=0
             dy(7) = 1000;
         else
             dy(7) = 0;
         end
     else
         dy(7) = 0;
     end
     dy(8) = theta(9);
     dy(9) = -(3-C)*theta(9)/4/u_m-(A_k/8/sqrt(F)*beta0/(alpha0+beta0/sqrt(u_m))^2+...
         3/8/u_m*alpha0/(alpha0+beta0/sqrt(u_m)))*theta(2)-...
         A_k/4/F/u_m*beta0/(alpha0*sqrt(u_m)+beta0)*theta(1)-...
         A_k/F/u_m*Phi;