function dy = calculate_bytheta_strong(u_m,theta,A_k,A_m,alpha_b,alpha_nu,...
    f1,f2,mu,kappa,coef_photon)
%{
psi = [Theta1, Theta1',Theta2,Theta2', Delta_ph , g_ph,
    theta1, theta1',theta2,theta2', nu_turnon]
%}

F = (1+kappa*sqrt(u_m/A_m)+8/3*u_m^2*(f1*(1-cos(theta(1)))+f2*mu^2*(1-cos(theta(3)))))...
    /(1-4/3*u_m^2*(f1*theta(2)^2+f2*theta(4)^2));
C = 1/F;

if theta(11) == 1
    Phi = (u_m*F*theta(2)*theta(8)+u_m*sin(theta(1))*theta(7)+1.5*F*theta(2)*theta(7)+...
        f2/f1*(u_m*F*theta(4)*theta(10)+u_m*mu^2*sin(theta(3))*theta(9)+1.5*F*theta(4)*theta(9))+...
        3/8/f1/u_m*theta(5)*(1+3/4*kappa*sqrt(u_m/A_m)))/...
        (u_m*F*(theta(2)^2+f2/f1*theta(4)^2)-A_k/f1);
    Phi_p_term = f1*theta(2)*theta(7)+f2*theta(4)*theta(9)...
        -theta(6)*C/4/u_m*(1+3/4*kappa*sqrt(u_m/A_m));
    %This is the term d(phi)/d(u_m)+phi/(2u_m)
else
    Phi = (u_m*F*theta(2)*theta(8)+u_m*sin(theta(1))*theta(7)+1.5*F*theta(2)*theta(7)+...
        f2/f1*(u_m*F*theta(4)*theta(10)+u_m*mu^2*sin(theta(3))*theta(9)+1.5*F*theta(4)*theta(9))+...
        3/8/f1/u_m*theta(5)*(1/(1+alpha_nu)+3/4*kappa*sqrt(u_m/A_m)))/...
        (u_m*F*(theta(2)^2+f2/f1*theta(4)^2)-A_k/f1);
    Phi_p_term = f1*theta(2)*theta(7)+f2*theta(4)*theta(9)...
        -theta(6)*C/4/u_m*(1/(1+alpha_nu)+3/4*kappa*sqrt(u_m/A_m));
end
if u_m<=1/A_k/10
    u_k = sqrt(4*A_k*u_m/3);
    Phi = -coef_photon*(-cos(u_k)/u_k^2+sin(u_k)/u_k^3)/2;
end
const_Del = theta(5)/2/u_m/(1+3/4*alpha_b*sqrt(u_m/A_m));
const_g = 2*f1*u_m*theta(2)^2*theta(6)+2*f2*u_m*theta(4)^2*theta(6)+...
    C/u_m*(1+3/4*kappa*sqrt(u_m/A_m))*theta(6);

     dy = zeros(11,1); % a column vector
     dy(1) = theta(2);
     dy(2) = -theta(2)/u_m*(5/2-2*u_m^2*(f1*theta(2)^2+f2*theta(4)^2)-...
         (1+3/4*kappa*(u_m./A_m).^(1/2))*C)...
         -sin(theta(1))*C;
     dy(3) = theta(4);
     dy(4) = -theta(4)/u_m*(5/2-2*u_m^2*(f1*theta(2)^2+f2*theta(4)^2)-...
         (1+3/4*kappa*(u_m./A_m).^(1/2))*C)...
         -mu^2*sin(theta(3))*C;
     dy(5) = 2*A_k*C/3*theta(6)+4*Phi_p_term+const_Del+const_g;
     dy(6) = -const_Del-const_g-2*Phi/u_m;
     dy(7) = theta(8);
     dy(8) = -theta(8)/u_m*(2.5-2*u_m^2*(f1*theta(2)^2+f2*theta(4)^2)...
         -C*(1+3/4*kappa*sqrt(u_m/A_m)))-...
         C*theta(7)*(A_k/u_m+cos(theta(1)))...
         +4*Phi_p_term*theta(2)-2*Phi*(theta(2)/u_m+C*sin(theta(1)));
     dy(9) = theta(10);
     dy(10) = -theta(10)/u_m*(2.5-2*u_m^2*(f1*theta(2)^2+f2*theta(4)^2)...
         -C*(1+3/4*kappa*sqrt(u_m/A_m)))-...
         C*theta(9)*(A_k/u_m+mu^2*cos(theta(3)))...
         +4*Phi_p_term*theta(4)-2*Phi*(theta(4)/u_m+C*mu^2*sin(theta(3)));
     if theta(11) == 1
         if theta(5)<=0
             dy(11) = 1000;
         else
             dy(11) = 0;
         end
     else
         dy(11) = 0;
     end